export const BEAUTIFUL_PROVIDER_NAMES: Record<string, string> = {
  openai: "OpenAI",
  openai_responses: "OpenAI (Responses API)",
  openai_codex: "OpenAI Codex",
  openrouter: "OpenRouter",
  groq: "Groq",
  anthropic: "Anthropic",
  claude_code: "Claude Code",
  deepseek: "DeepSeek",
  google_gemini: "Google Gemini",
  ollama: "Ollama",
  lmstudio: "LM Studio",
  vllm: "vLLM",
  xai: "xAI",
  xai_responses: "xAI (Responses API)",
  custom: "Custom Provider",
};
