pub mod actor;
pub mod autonomous_workflows;
pub mod chat_reactions;
pub mod conversation_ledger;
pub mod diagnostics;
pub mod drafts;
pub mod events;
pub mod facts;
pub mod humor;
pub mod issues;
pub mod jobs;
pub mod memory_lifecycle;
pub mod observers;
pub mod opportunities;
pub mod policy;
pub mod pulse;
pub mod pulse_inject;
pub mod runtime_queue;
pub mod scheduler;
pub mod settings;
pub mod snapshot;
pub mod speech_policy;
pub mod state;
pub mod storage;
pub mod types;
pub mod user_activity;
pub mod voice_service;
pub mod workflows;

#[cfg(test)]
mod tests;
